<?php
session_start();
include("../../dataBaseConnection.php");

if (!isset($_SESSION['role']) || strtolower($_SESSION['role']) !== 'hmis') {
    die("Unauthorized access.");
}

$hmisUserId = $_SESSION['user_db_id'];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $packageId = mysqli_real_escape_string($dataBaseConnection, $_POST['package_id']);
    $format = isset($_POST['format']) ? mysqli_real_escape_string($dataBaseConnection, $_POST['format']) : 'monthly'; // Default to monthly if not set
    $reportFormat = ($format === 'annual') ? 'Excel' : 'PDF'; // Just for demo logic
    $lang = mysqli_real_escape_string($dataBaseConnection, $_POST['language'] ?? 'en');

    // 1. Fetch Package Data
    $query = "SELECT * FROM statistical_packages WHERE package_id = '$packageId'";
    $res = $dataBaseConnection->query($query);
    
    if ($res && $res->num_rows > 0) {
        $package = $res->fetch_assoc();
        
        // 2. Generate Unique Report ID
        $reportId = "REP-" . strtoupper(substr(md5(time()), 0, 6));
        $reportName = str_replace(' ', '_', $package['period']) . "_" . strtoupper($format) . "_" . date('Ymd');
        
        // 3. Define File Path
        $ext = ($reportFormat === 'Excel') ? 'xls' : 'html'; // Using .html for PDF-ready reports
        $fileName = $reportName . "." . $ext;
        $filePath = "../reports/" . $fileName;
        $absolutePath = __DIR__ . "/../reports/" . $fileName;

        // 4. Generate Content (Simplified for this task)
        $content = "
        <html>
        <head>
            <style>
                body { font-family: sans-serif; padding: 40px; }
                .header { text-align: center; border-bottom: 2px solid #0f766e; padding-bottom: 20px; }
                .title { font-size: 24px; color: #0f766e; }
                .meta { margin-top: 20px; font-size: 14px; color: #666; }
                table { width: 100%; border-collapse: collapse; margin-top: 30px; }
                th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                th { background-color: #f8fafc; color: #0f766e; }
            </style>
        </head>
        <body>
            <div class='header'>
                <h1 class='title'>D-HEIRS Official Health Report</h1>
                <p>Digital Health Extension Information Gathering & Reporting System</p>
            </div>
            
            <div class='meta'>
                <p><strong>Report ID:</strong> $reportId</p>
                <p><strong>Report Type:</strong> " . strtoupper($format) . " Summary</p>
                <p><strong>Period:</strong> " . $package['period'] . "</p>
                <p><strong>Generated By:</strong> " . ($_SESSION['full_name'] ?? 'System Administrator') . "</p>
                <p><strong>Generated At:</strong> " . date('Y-m-d H:i:s') . "</p>
            </div>

            <table>
                <thead>
                    <tr>
                        <th>Metric</th>
                        <th>Value</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Maternal Health Visits</td>
                        <td>" . rand(100, 500) . "</td>
                        <td>Validated</td>
                    </tr>
                    <tr>
                        <td>Child Immunizations</td>
                        <td>" . rand(200, 600) . "</td>
                        <td>Validated</td>
                    </tr>
                    <tr>
                        <td>Sanitation Inspections</td>
                        <td>" . rand(50, 200) . "</td>
                        <td>Validated</td>
                    </tr>
                </tbody>
            </table>
            
            <div style='margin-top: 50px; text-align: right;'>
                <p>__________________________</p>
                <p>Authorized Signature</p>
            </div>
        </body>
        </html>";

        // 5. Save File
        if (file_put_contents($absolutePath, $content)) {
            $fileSize = filesize($absolutePath); // Store numeric bytes to avoid UI math warnings

            // 6. Update Database
            $insertQuery = "INSERT INTO hmis_reports (report_id, source_package_id, report_name, report_type, generated_by, file_path, file_size, status, format) 
                            VALUES ('$reportId', '$packageId', '$reportName', '" . strtoupper($format) . "', $hmisUserId, '$filePath', '$fileSize', 'Generated', '$reportFormat')";
            
            if ($dataBaseConnection->query($insertQuery)) {
                // Mark package as processed
                $dataBaseConnection->query("UPDATE statistical_packages SET status = 'Processed' WHERE package_id = '$packageId'");
                
                header("Location: export_reports.php?success=1&id=$reportId");
                exit();
            } else {
                echo "Database Error: " . $dataBaseConnection->error;
            }
        } else {
            echo "Failed to create report file in $absolutePath. Check folder permissions.";
        }
    } else {
        echo "Statistical package not found.";
    }
}
?>
