-- D-HEIRS HMIS Module Database Setup
-- This script creates tables for HMIS official reports, analytics, and DHIS2 logs.

-- 1. Statistical Packages (Data received from Linkage Focal Person)
-- These are the validated summaries that HMIS Officer processes.
CREATE TABLE IF NOT EXISTS statistical_packages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    package_id VARCHAR(50) UNIQUE NOT NULL,
    period VARCHAR(50) NOT NULL,
    focal_person_id INT NOT NULL,
    focal_person_name VARCHAR(255),
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) DEFAULT 'Pending', -- Pending, Processed
    data_summary JSON, -- Store aggregated numbers/KPIs for easy retrieval
    FOREIGN KEY (focal_person_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. HMIS Official Reports (Generated by HMIS Officer)
CREATE TABLE IF NOT EXISTS hmis_reports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    report_id VARCHAR(50) UNIQUE NOT NULL,
    source_package_id VARCHAR(50),
    report_name VARCHAR(255) NOT NULL,
    report_type VARCHAR(100) NOT NULL, -- Monthly, KPI, Annual
    generated_by INT NOT NULL,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    file_path VARCHAR(255),
    file_size VARCHAR(50),
    status VARCHAR(50) DEFAULT 'Generated', -- Generated, Submitted
    format VARCHAR(20) DEFAULT 'PDF',
    notes TEXT,
    FOREIGN KEY (generated_by) REFERENCES users(id),
    FOREIGN KEY (source_package_id) REFERENCES statistical_packages(package_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. DHIS2 Submission Logs
CREATE TABLE IF NOT EXISTS dhis2_submissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    submission_id VARCHAR(50) UNIQUE NOT NULL,
    report_id VARCHAR(50) NOT NULL,
    submitted_by INT NOT NULL,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dhis2_response_code VARCHAR(10),
    dhis2_reference VARCHAR(100),
    status VARCHAR(50) DEFAULT 'Success', -- Success, Failed
    FOREIGN KEY (submitted_by) REFERENCES users(id),
    FOREIGN KEY (report_id) REFERENCES hmis_reports(report_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Analytics Summary (For Dashboard Visualizations)
-- This table can be updated via triggers or scheduled tasks to speed up dashboard loading.
CREATE TABLE IF NOT EXISTS hmis_analytics_summary (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(100) NOT NULL, -- e.g., 'Reports_Monthly', 'KPI_Accuracy'
    metric_name VARCHAR(100) NOT NULL,
    metric_value DECIMAL(15, 2),
    period VARCHAR(50),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert Seed Data for Demonstration
INSERT IGNORE INTO statistical_packages (package_id, period, focal_person_id, focal_person_name, status) VALUES
('STAT-2025-001', 'January 2025', 1, 'Abebe Kebede', 'Pending'),
('STAT-2024-124', 'December 2024', 1, 'Sara Tekle', 'Processed');

INSERT IGNORE INTO hmis_reports (report_id, source_package_id, report_name, report_type, generated_by, file_size, status, format) VALUES 
('REP-124', 'STAT-2024-124', 'Monthly_Summary_Dec_2024', 'Monthly', 2, '2457600', 'Generated', 'PDF'),
('REP-132', 'STAT-2024-112', 'KPI_Report_Q4_2024', 'KPI', 2, '1153433', 'Submitted', 'Excel');

INSERT IGNORE INTO dhis2_submissions (submission_id, report_id, submitted_by, dhis2_response_code, dhis2_reference) VALUES
('SUB-101', 'REP-132', 2, '200', 'DHIS2-REF-9988');
